### PR TITLE
Limit prefill batch size

### PR DESCRIPTION
**Pull request by tzielinski-habana**
Limit prefill batch size so that we avoid recompilations. This can be controlled with an env var VLLM_PROMPT_BS_BUCKET_MAX

### CODE REVIEW

**Review by madamczykhabana — CHANGES_REQUESTED** [review]
Also please change warmup logic in habana_model_runner.py so that we warm-up prompt only up to this value

**Review by madamczykhabana — CHANGES_REQUESTED** [review]
Please also change  _setup_buckets in habana_model_runner.py so that we don't warm-up configurations that are never going to be run

**Comment by szutenberg** [comment]
AR: @szutenberg test with VLLM_PROMPT_BS_BUCKET_MAX=16

**Comment by tae-su-kim** [comment]
Hi guys, I was separately working on limiting the number of prefill graphs and stumbled upon this PR. I managed to remove all additional prefill graph compilations after initial graph capture by comparing max_num_batched_tokens and number of padded tokens for prefill during prefill scheduling(https://github.com/SqueezeBits/vllm-fork/commit/7da8b0b26d7cc32a4153f96e95ee88661d247bef).

With
1. llama-3-8B on a single Gaudi-2 device
2. max-model-len 3072 (2K input / 1K output case)
3. max_num_batched_tokens 3072
4. max-num-seqs 128
I could observe prefill latency decreasing from ~73 seconds to ~28 seconds in hpu_graph mode on a custom dataset (1024 queries sampled from OpenOrca). I think additional latency improvement rather than reduced compilation time comes from a side effect of preventing longer sequences being batched with shorter sequences, which will cause a lot of unnecessary padding.
If you are interested, I will open a PR. Thanks.

**Comment by madamczykhabana** [comment]
Hi @tae-su-kim. Thanks for reaching out! I took a look at your code and it's an interesting idea that tackles the problem from another angle. Please create the PR. We'll move the discussion there.

**Pull request merged**
